# Continuous integration:
# Clone the repository to temporary folder
# Build the container
# Run lint check
# Run tests
# Deploy (commit to github)

stages:
  - build
#  - lint
#  - test
#  - deploy
#  - cleanup


variables:
  MY_IMAGE_NAME: "my_image"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - docker info
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/alexbenfica/check-links .
    - docker push registry.gitlab.com/alexbenfica/check-links


#lint:
#  stage: lint
#  image: docker:latest
#  services:
#    - docker:dind
#  tags:
#    - docker
#  before_script:
#    - docker info
#  script:
#    - docker run my-docker-image uptime



#  before_script:
#    - docker build -f Dockerfile -t ci-project-build-$CI_PROJECT_ID:$CI_BUILD_REF .
#  script:
#    - docker run -t ci-project-build-$CI_PROJECT_ID:$CI_BUILD_REF
#


# How to register the docker runner
#sudo gitlab-runner register -n \
#  --url GITLAB_URL \
#  --registration-token REGISTRATION_TOKEN \
#  --executor docker \
#  --description "Docker Runner" \
#  --docker-image "docker:latest" \
#  --docker-privileged

