# Continuous integration \ deployment

stages:
#  - build
#  - test
  - deploy


variables:
  TEST_IMAGE_NAME: "registry.gitlab.com/alexbenfica/check-links:test"
  PROD_IMAGE_NAME: "registry.gitlab.com/alexbenfica/check-links"

#
#build_test_container:
#  stage: build
#  image: docker:latest
#  services:
#    - docker:dind
#  tags:
#    - docker
#  script:
#    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
#    - docker build -t $TEST_IMAGE_NAME .
#    - docker push $TEST_IMAGE_NAME
#
#
#
#run_tests:
#  stage: test
#  image: docker:latest
#  services:
#    - docker:dind
#  tags:
#    - docker
#  script:
#    - docker run $TEST_IMAGE_NAME pytest /tests
#    #- docker run $TEST_IMAGE_NAME pylint --max-line-length=120 /app/*.py


#
#create_final_container:
#  stage: deploy
#  image: docker:latest
#  services:
#    - docker:dind
#  tags:
#    - docker
#  only:
#    - master
#  script:
#    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
#    - docker build -t $PROD_IMAGE_NAME .
#    - docker push $PROD_IMAGE_NAME
#
#

publish_to_pypi:
  stage: deploy
  image: python:3
  only:
    - master
  script:
    - apt update
    - apt install -y python3-pip
    - pip3 install -U wheel
    - pip3 install -U setuptools
    - pip3 install twine
    - python setup.py sdist bdist_wheel
    - twine upload -u alexbenfica -p $PYPI_PASSWORD dist/*
