# Continuous integration:
# Clone the repository to temporary folder
# Build the container
# Run lint check
# Run tests
# Deploy (commit to github)

stages:
  - build
#  - lint
#  - test
#  - deploy
#  - cleanup


build:
  stage: build
  tags:
    - docker
  before_script:
    - docker info
  script:
    - docker build -t my-docker-image .
    - docker run my-docker-image pwd


#  before_script:
#    - docker build -f Dockerfile -t ci-project-build-$CI_PROJECT_ID:$CI_BUILD_REF .
#  script:
#    - docker run -t ci-project-build-$CI_PROJECT_ID:$CI_BUILD_REF
#



