# Continuous integration \ deployment

stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: "registry.gitlab.com/alexbenfica/check-links"


build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  tags:
    - docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME


test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  tags:
    - docker
  script:
    - docker run $IMAGE_NAME pytest /tests


deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  tags:
    - docker
  script:
    # merge into master
    - ls





