# Continuous integration:
# Clone the repository to temporary folder
# Build the container
# Run lint check
# Run tests
# Deploy (commit to github)

stages:
  - build
#  - lint
#  - test
#  - deploy
#  - cleanup


build:
  stage: build
  tags:
    - docker
  before_script:
    - docker build -f Dockerfile -t ci-project-build-$CI_PROJECT_ID:$CI_BUILD_REF .
  script:
    - docker run -t ci-project-build-$CI_PROJECT_ID:$CI_BUILD_REF





