# Continuous integration:
# Clone the repository to temporary folder
# Build the container
# Run lint check
# Run tests
# Deploy (commit to github)


image: python:3
services:
  - docker:dind


stages:
  - build
#  - lint
#  - test
#  - deploy
#  - cleanup


build:
  stage: build
  tags:
    - docker
  before_script:
    - docker info
  script:
    - docker build -t my-docker-image .
    - docker run my-docker-image pwd
    - docker run my-docker-image ls -las


#  before_script:
#    - docker build -f Dockerfile -t ci-project-build-$CI_PROJECT_ID:$CI_BUILD_REF .
#  script:
#    - docker run -t ci-project-build-$CI_PROJECT_ID:$CI_BUILD_REF
#


# How to register the docker runner
#sudo gitlab-runner register -n \
#  --url GITLAB_URL \
#  --registration-token REGISTRATION_TOKEN \
#  --executor docker \
#  --description "Docker Runner" \
#  --docker-image "docker:latest" \
#  --docker-privileged

